/*******************************************************************************
 * Copyright (c) 2017 Operation Asha.
 * All rights reserved. This program and the accompanying materials
 * are copyright of Operation Asha.
 *
 * Contributors:
 *     Abhishek Sinha - Author
 *******************************************************************************/
package org.opasha.eCompliance.ecompliance.modal.wcf.Patient;

import java.util.Date;

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class Patient_Hiv {
	public String Treatment_ID;
	public String Final_Result;
	public String Screening_Result;
	public String Created_By;
	public Date Creation_Timestamp;
	public boolean Is_Deleted;
}
